language: node_js
node_js:
- "8"
- "7"
- "6"
- "5"
- "4"
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  
deploy:
  provider: npm
  email: wouter.dullaert@gmail.com
  api_key:
    secure: "DO//7g14yaFsqw01WtMhlP8J9mvG8YP1iIEhI0HaUVf0lSB5ggylAvlhb727pAvu0ltJmeVZSlb8NwYRO0np9JAzdTIaL6a9QFTgYKaybNY+R2qwcuoSl2Vt73sIk2iQP1z+zAJhzRP1vALDNmcRsqgttgxdIN1w6LQYsJ+aX3DsB/P88+5tn2KlyV4e1TIiYhpXDjkKiaeFtmzmvDhGii2gE2Qw7GPnhQ+oGVD6zCDZT7F5kjJOCk/QQQQREtG5zI/Ml0n+gs+ugbb0Y+/v71q6AONoBco8OH2K1nNDIW8cA6/8xyDRygsT0ZRLvi1Uo0YS1usY8IxS0t5cy6RqvpShXz99gnNZhlg0RcnV5ZIfi5PiLhWYxvX/gbr23ggmmxa84X5mLDIFcDYA/h29aT8WuRl0Nn0D4OVt097UcoePM+1zfuEWgVcl5oZ5lN3CgadkfNBztxT0rhJRr4lTX7ugdrigIGVzgzeEVkQqBJcgBWuzr80jzn79wh6hJbt1QJciV/XTS/W/Gz1e6+Sae6E/mXSnSTupzKYK2Hl4sv0znolECRmkZsvefMQJca7EGkhixMgktfng0eRe1K1J/u8eBbDj7pg5nMBAUwsxwBRSipVZOVcZSnPuz1kpWzyGm6i6ZFrgU+OCqQZT2VCxl1IXdnfYdOiPl5z37mSfZvk="
  on:
    tags: true
    node: "6"

addons:
    code_climate:
        repo_token: 65371745d78cfbd0cb2f40bee7545dd63dc2541b8fffec57588adad0292bce95
